export const pupList = [
    {
      id: 1,
      name: "Luna",
      email: "luna@email.com",
      isCute: true,
      age: 10,
      ownerId: 1,
      tricks: [
        { id: 2, title: "Lay Down" },
        { id: 3, title: "Jump through flaming hoop" },
      ],
    },
    {
      id: 2,
      name: "PoePoe",
      email: "poe@email.com",
      isCute: true,
      age: 23,
      ownerId: 1,
      tricks: [],
    },
    {
      id: 3,
      name: "Bella",
      email: "bella@email.com",
      isCute: true,
      age: 30,
      ownerId: 2,
      tricks: [{ id: 1, title: "Sit" }],
    },
    {
      id: 4,
      name: "LeBron",
      email: "LeBron@email.com",
      isCute: true,
      age: 6,
      ownerId: 2,
      tricks: [{ id: 2, title: "Lay Down" }],
    },
    {
      id: 5,
      name: "Curry",
      email: "curry@email.com",
      isCute: true,
      age: 19,
      ownerId: 3,
      tricks: [],
    },
    {
      id: 6,
      name: "FunnyGirl",
      email: "funnygirl@email.com",
      isCute: true,
      age: 1,
      ownerId: 3,
      tricks: [],
    },
    {
      id: 7,
      name: "FunnyBoy",
      email: "FunnyBoy@email.com",
      isCute: true,
      age: 45,
      ownerId: 3,
      tricks: [],
    },
  ];